### PR TITLE
Option to select jellyfin-tizen-build package and release version

### PR DESCRIPTION
**Pull request by pgodzwa**
This PR adds possibility to:
select jellyfin-tizen-build package (Jellyfin / Jellyfin-TrueHD / Jellyfin-master / Jellyfin-master-TrueHD / Jellyfin-secondary) as second argument. By default, Jellyfin option is used.
select jellyfin-tizen-build release tag as third argument. By default, latest version is used. This is useful if you want to install older Jellyfin Tizen Client version.

### CODE REVIEW

**Comment by Georift** [comment]
Amazing thanks for the patch! I'll have a look at this and the other PR tonight 🙂

**Comment by pgodzwa** [comment]
Added option to also select specified release tag by providing URL as third argument. Hopefully it fully fixes https://github.com/Georift/install-jellyfin-tizen/issues/23 ;)

**Comment by bleach1520** [comment]
Thanks, bro😘

**Comment by Georift** [comment]
Tested all the options working great! Thanks for doing that extra bit completely unprompted! :grin:

**Comment by Georift** [comment]
The latest container image contains this build.

**Pull request merged**
