### PR TITLE
fix: obtain device name from sdb

### PR DESCRIPTION
**Pull request by domenicoblanco**
Some devices have different names available in the apis, this PR changes the way to obtain the device name from the API to the suggested `sdb devices` command.

Tested with an UE50JU6900 and correctly returns UJU6900.
It's not the same as asked in #11 but probably could close it

### CODE REVIEW

**Comment by Georift** [comment]
Hmm just giving this a test locally looks like my version of SDB has a slightly different output.

When I run the command you added here I get `devices` as well as my TV name:

```console
root@9857af18aea2:~# sdb devices
List of devices attached
10.1.1.10:26101         device          UA65RU7100WXXY
root@9857af18aea2:~# sdb devices | grep -E '\s{5}\w+' -o
        device
        UA65RU7100WXXY
root@9857af18aea2:~# sdb devices | grep -E '\s{5}\w+' -o | xargs
device UA65RU7100WXXY

```

Just out of interest what do you see in this case?

**Comment by domenicoblanco** [comment]
I'm trying from a container with the image from `vitalets/tizen-webos-sdk`, my output is a bit different but with some tweak to the regex, I think that could be handled

```
root@d8a10f48cc24:~# sdb devices
List of devices attached 
192.168.2.76:26101  	device    	UJU6900
root@d8a10f48cc24:~# sdb devices | grep -E '\s{5}\w+' -o | xargs
UJU6900
```

**Comment by Georift** [comment]
Thanks for the updated fix, I'll check this out shortly. 🤞

**Comment by Georift** [comment]
Still haven't forgotten, sorry for the delay!

**Comment by domenicoblanco** [comment]
Don’t worry and take your time! c:

**Comment by formeo14** [comment]
Is there a plan when this PR will be merged?
This should fix the same issue with my TV and nothing happened the last two months😔

**Comment by domenicoblanco** [comment]
> Is there a plan when this PR will be merged? This should fix the same issue with my TV and nothing happened the last two months😔

Hi! If you feel comfortable in entering your container shell and edit one file with a terminal, you could try to edit your entrypoint.sh (if I remember well is in the home directory) according to my PR.
In case you need help, feel free to ask c:

**Comment by formeo14** [comment]
Thanks that worked👍

**Comment by domenicoblanco** [comment]
Glad to hear that c:

**Comment by Georift** [comment]
Hey @domenicoblanco cheers for the change, apologies it's taken me to long to test it.

Lets give it a merge now, people can raise an issue if it break something 🤞  Thanks again for this.

**Comment by domenicoblanco** [comment]
Don't worry about it and let's hope it works for everyone! c:

**Comment by nahcir** [comment]
Hi,
even after the fix I'm still having this issue on multiple (older) TVs. I checked Georift's Docker Hub page (https://hub.docker.com/r/georift/install-jellyfin-tizen), and it seems like the docker container itself hasn't been updated in over four months, so I suspect that's the reason. Is there plan on uploading an updated container to the Docker Hub page anytime soon?
Thanks!

**Comment by Georift** [comment]
My apologies @nahcir I haven't updated the docker container. I will push an update this afternoon.

In the mean time if you clone this repo and [follow these steps](https://github.com/Georift/install-jellyfin-tizen/issues/11#issuecomment-2313003641) you can use the latest version.

**Comment by nahcir** [comment]
@Georift Thanks for the info, I'll just wait for you to update the container. Thanks in advance :-)!

**Pull request merged**
